# Get bun
FROM oven/bun

# Create app directory
RUN mkdir -p /usr/src/app

# Set work directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./frontend/package*.json /usr/src/app/

# Install typescript and node modules
RUN bun install typescript -g 
RUN bun install

# Copy the entire frontend directory
COPY ./frontend/ /usr/src/app

# Set environment variable
ENV VITE_REACT_APP_BASE_URL=https://lsag-financial-pangea.lsag.net

# Build the app
# RUN bun run build

CMD [ "bun", "run", "build" ]