#FROM node:12.13-alpine
FROM node:18.17.0-alpine3.18 

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./backend/package*.json /usr/src/app/

RUN npm install typescript -g 
RUN npm install

COPY ./backend/ /usr/src/app

RUN npx prisma generate

CMD [ "npm", "run", "dev", "--", "--host" ]