#FROM node:12.13-alpine
FROM node:18.17.0-alpine3.18 

RUN sed -i 's/providers = provider_sect/providers = provider_sect\n\
ssl_conf = ssl_sect\n\
\n\
[ssl_sect]\n\
system_default = system_default_sect\n\
\n\
[system_default_sect]\n\
Options = UnsafeLegacyRenegotiation/' /etc/ssl/openssl.cnf

COPY ./LSAG-Root.cer /usr/local/share/ca-certificates/LSAG-Root.crt
RUN cat /usr/local/share/ca-certificates/LSAG-Root.crt >> /etc/ssl/certs/ca-certificates.crt && \
    apk --no-cache add \
        curl


ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools


RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./backend/package*.json /usr/src/app/

RUN npm install typescript -g 
RUN npm install

COPY ./backend/ /usr/src/app

RUN npx prisma generate

CMD [ "npm", "run", "dev", "--", "--host" ]